version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202201-02
    working_directory: /home/circleci/.go_workspace/src/github.com/hashicorp/vault-plugin-auth-kerberos
    steps:
      - checkout
      - run:
          name: "Install Go"
          command: |
            # taken from https://golang.org/dl/, will need to be updated on version bump
            sha256_linux_amd64='f242a9db6a0ad1846de7b6d94d507915d14062660616a61ef7c808a76e4f1676'
            filename="go1.17.2.linux-amd64.tar.gz"
            pushd /tmp
            hash="$(curl -fL "https://golang.org/dl/${filename}" | tee "${filename}" | sha256sum | cut -f 1 -d ' ')"
            [ "${sha256_linux_amd64}" = "${hash}" ] || (echo "${filename} has an invalid hash ${hash}" >&2 ; exit 1)
            rm -rf /var/tmp/go &> /dev/null
            tar -xpf "${filename}" -C /var/tmp/.
            echo 'export GOROOT=/var/tmp/go' >> $BASH_ENV
            echo "export PATH=/var/tmp/go/bin:$PATH" >> $BASH_ENV
            popd
      - run:
          name: "Go version"
          command: |
            go version
      - run:
          name: "Run Go Tests"
          command: |
            make test
      - run:
          name: "Run Build"
          command: |
            go get github.com/mitchellh/gox
            make dev
      - run:
          name: "Run Integration Tests"
          command: |
            ./scripts/integration_env.sh
